name: Lib-ML

on:
  push:
    branches:
      - preprocessing_lib
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with pylint and flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Lint with pylint
        run: poetry run pylint $(git ls-files '*.py')

      - name: Lint with flake8
        run: poetry run flake8 .
