name: Lib-ML

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with pylint & flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Lint with pylint
        run: poetry run pylint $(git ls-files '*.py') remla_preprocess/ tests/

      - name: Lint with flake8
        run: poetry run flake8 .

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report -m
          poetry run coverage html

      - name: Check coverage threshold
        run: poetry run coverage report --fail-under=100
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov/

  publish:
    name: Build and publish library
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Update lib version
        run: bash update_version.sh

      - name: Build lib
        run: poetry build

      - name: Publish lib
        run: poetry run twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: pypi-${{secrets.PYPI_TOKEN}}