name: Lib-ML

on:
  push:
    branches:
    - preprocessing_lib 
    tags:
    - 'v*' 

jobs:
  publish:
    if: startsWith(github.event.ref, 'refs/tags/v')
    name: Lint with pylint & flake8 and publish library 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Lint with pylint
        run: poetry run pylint $(git ls-files '*.py')

      - name: Lint with flake8
        run: poetry run flake8 .

      - name: Build lib
        run: poetry build 
      
      - name: Publish lib 
        run: poetry run twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}